name: Compare PR stats

on: [pull_request]

concurrency:
  # only allow one run of this workflow per branch, otherwise the comment could
  # be overwritten by an earlier commit that runs slower than the latest commit
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  base-branch:
    uses: ./.github/workflows/record-pr-stats.yml
    with:
      ref: ${{ github.event.pull_request.base.sha }}

  head-branch:
    uses: ./.github/workflows/record-pr-stats.yml
    with:
      ref: ${{ github.sha }}

  compare-pr-stats:
    runs-on: ubuntu-latest
    needs: [base-branch, head-branch]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: 18
          cache: 'npm'
      
      - run: npm ci

      - name: Leave comment
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          script: |
            const leaveComment = require('./.github/leave-pr-stats-comment.js')

            await leaveComment(github, context, require, ${{ toJSON(needs) }})
